### ISSUE TITLE
Add support for Nix

### ISSUE THREAD

**Issue by lilyball** [stkb/Rewrap#145]
Line comments in Nix start with `#`, block comments with `/* … */`. Nix also has two string types, both of which support multiline text; strings delimited with `"` and strings delimited with `''` (though in practice multiline strings generally use `''`).

[Full documentation](https://nixos.org/nix/manual/#ch-expression-language)

**Comment by stkb** [comment]
This should now work since version 1.10.0, if you have a nix plugin installed.

**Comment by lilyball** [comment]
I have Rewrap 1.10.1 installed as well as the Nix plugin (bbenoist.nix), but wrapping is still not detecting comments.

**Comment by lilyball** [comment]
I just verified the `nix.language-configuration.json` file for the extension does declare comments:

```json
{
  "comments": {
    "lineComment": "#",
    "blockComment": [ "/*", "*/" ]
  },
  "brackets": [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"]
  ],
  "autoClosingPairs": [
    { "open": "{", "close": "}" },
    { "open": "[", "close": "]" },
    { "open": "(", "close": ")" },
    { "open": "\"", "close": "\"", "notIn": ["string"] },
    { "open": "''", "close": "''", "notIn": ["string"] },
  ],
  "surroundingPairs": [
    [ "(", ")" ],
    [ "[", "]" ],
    [ "{", "}" ],
    [ "<", ">" ],
    [ "\"", "\"" ]
  ]
}
```

**Comment by stkb** [comment]
That's annoying because it's working fine for me (with the same extension) 😕 Any errors/warnings in the developer console?


<img src="https://user-images.githubusercontent.com/6125444/82685048-e071e280-9c53-11ea-9ece-575186b60965.gif" width="500">

**Comment by stkb** [comment]
Could you try another language/extension, for example [Haxe](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe) that was confirmed to work by another user. Then we know if the feature isn't working at all for you.

Further to that I'll add some more logging to try to diagnose the issue.

**Comment by lilyball** [comment]
This doesn't appear to work with Haxe either. I just installed the extension, created a new scratch buffer, set the file type to Haxe, wrote the following

```haxe
// a
// b
c
d
```

and pressed alt-q and got

```haxe
// a // b c d
```

If by "developer console" you mean the web inspector from "Toggle Developer Tools", there's nothing that looks relevant, just some warnings about extensions overwriting grammar file mappings for a couple of languages.

**Comment by stkb** [comment]
Thanks, yeah it's not working for you then. The next version will be releasing this weekend; I'll add some more logging to it first and we'll take it from there.

**Comment by stkb** [comment]
I decided not to put the extra logging into the release version but into a beta version instead. Could you [try out the latest beta release](https://github.com/stkb/Rewrap/releases/tag/beta)? And then try a nix file again, and yes look in the web inspector in Toggle Developer Tools.

When it works it should look something like this:
```
...

Extension bbenoist.Nix
  contributes 'nix'
    with C:\Users\Me\.vscode\extensions\bbenoist.nix-1.0.1\nix.configuration.json

...

Looking for extension for language: nix
Inspecting JSON file C:\Users\Me\.vscode\extensions\bbenoist.nix-1.0.1\nix.configuration.json
Using.
```

**Comment by lilyball** [comment]
Ah hah! I'm using a modified Nix extension and my `nix.language-configuration.json` had a trailing comma a final array element. This isn't allowed by standard JSON but VSCode's JSON parser accepts it. So this meant the extension worked fine in VSCode except it couldn't be parsed by your extension.

I don't know why Haxe didn't work for me though, unless your extension bailed on parsing language configurations in general when it encountered the JSON error in the Nix extension.

In any case, removing that trailing comma and trying again seems to work.

**Comment by lilyball** [comment]
FWIW I'm surprised the parsing error wasn't logged by the release version of your extension.

**Comment by stkb** [comment]
Not sure what sort of JSON parser is used by VSCode (I guess a custom one). Here comment-json is used (which allows the comments but I guess not trailing commas).

> FWIW I'm surprised the parsing error wasn't logged by the release version of your extension.

It wasn't logging it. It was just ignoring it and moving on :)

Glad it's worked out for you

**Comment by lilyball** [comment]
It looks like there’s a library [json5](https://www.npmjs.com/package/json5) that not only supports comments but also trailing commas. It sounds like `comment-json`’s strength is in preserving comments so they can be serialized back out again, which doesn’t seem useful for what you’re doing.
