### ISSUE TITLE
Correctly rewrap Python docstring

### ISSUE THREAD

**Issue by albireox** [stkb/Rewrap#89]
When I have a docstring such as

```python
"""A definition

Parameters
----------
object1 : type1
    Some text here
object2 : type2
    A very very very long line that continues and continues and continues and goes on.

"""
```

when I run Rewrap, doesn't matter whether with `wholeComment=True` or `False`, I get

```python
"""A definition

Parameters
----------
object1 : type1 Some text here object2 : type2 A very very very long line that
    continues and continues and continues and goes on.

"""
```

unless I manually select the line to wrap. Ideally Rewrap would be able to wrap this correctly and consider every "object" a paragraph. Alternatively there could be an option to rewrap only the current line (which could be useful in a number of situations).

**Comment by stkb** [comment]
Yeah this is because the content is parsed as markdown, whereas Python documentation actually uses restructuredText. Once I add support for that (#88), it'll be the markup language used for Python, which should fix this.

**Comment by hkunzhe** [comment]
It seems that Rewrap has already added support for restructuredText in #88. However, I still have the same issue with @albireox.
Did I do something wrong?

**Comment by adrn** [comment]
Encountering this myself and just found this issue! Any pointers to how we could help implement a fix for this? I would love to turn on autowrap but it messes up my docstrings, so I have to wrap everything manually in there...

**Comment by shaperilio** [comment]
I think #278 is related

**Comment by stkb** [comment]
Closing this in favor of #88
